const express = require('express');
const bodyParser = require('body-parser');
const pptxgen = require('pptxgenjs');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = 3000;

app.use(bodyParser.json({ limit: '50mb' }));

app.post('/render', (req, res) => {
    try {
        const { slide_plan, course_id, output_path } = req.body;

        if (!slide_plan) {
            return res.status(400).json({ error: "Missing slide_plan" });
        }

        const pres = new pptxgen();
        pres.layout = 'LAYOUT_WIDE'; // 13.33 x 7.5 inches

        // Metadata
        pres.title = slide_plan.title || `Course ${course_id}`;
        pres.author = 'AI Course Creator';

        // Title Slide
        let slide = pres.addSlide();
        // 13.33 * 0.8 = 10.6
        slide.addText(slide_plan.title || `Course PPT`, { x: 1, y: 1, w: 10.6, h: 1, fontSize: 36, align: 'center', bold: true });
        slide.addText("Generated by AI Authoring", { x: 1, y: 2.5, w: 10.6, h: 0.5, fontSize: 18, align: 'center', color: '666666' });

        // Content Slides
        const slidesData = slide_plan.slides || [];
        slidesData.forEach((s) => {
            let slide = pres.addSlide();

            // Slide Title (90% -> 12 inches)
            slide.addText(s.title || "Untitled Slide", { x: 0.5, y: 0.5, w: 12, h: 0.8, fontSize: 24, bold: true, color: '003366' });

            // Bullets
            const bullets = s.bullets || [];
            if (Array.isArray(bullets)) {
                // Ensure bullet items are strings
                const bulletItems = bullets.map(b => ({ text: String(b), options: { fontSize: 18, breakLine: true } }));
                slide.addText(bulletItems, { x: 0.5, y: 1.5, w: 12, h: 3.5, bullet: true });
            } else if (typeof bullets === 'string') {
                slide.addText(bullets, { x: 0.5, y: 1.5, w: 12, h: 3.5, fontSize: 18 });
            }

            // Speaker Notes
            if (s.speaker_notes) {
                slide.addNotes(s.speaker_notes);
            }

            // Demo Patch: Illustration Placeholder
            // Normalize illustration prompt field (Boss Requirement)
            const prompt = s.illustration_prompt || s.illustration || s.image_prompt || "";

            if (prompt) {
                // Add a placeholder rectangle
                // FIX: Use pptxgen.ShapeType.rect per Boss Requirement
                // Position below content?
                // y: 5.2, h: 2.0 (To fit in 7.5 total height)
                slide.addShape(pptxgen.ShapeType.rect, {
                    x: 0.5, y: 5.2, w: 12, h: 2.0,
                    fill: { color: 'F0F0F0' },
                    line: { color: 'CCCCCC', width: 1, dashType: 'dash' }
                });
                // Add icon/text
                slide.addText("🖼️ ILLUSTRATION PLACEHOLDER", {
                    x: 0.5, y: 5.3, w: 12, h: 0.5,
                    align: 'center', fontSize: 14, color: '666666', bold: true
                });
                slide.addText(prompt, {
                    x: 1.0, y: 5.8, w: 11, h: 1.2,
                    align: 'center', fontSize: 10, color: '888888', italic: true
                });
            }
        });

        // Determine output path
        // If output_path is provided (absolute path in shared volume), use it.
        // Otherwise default to a temp location or a standard location.
        // The container needs write access to this path (should be mounted volume).

        const finalPath = output_path || path.join('/app/generated_data/ppt', `course_${course_id}_preview.pptx`);
        const dir = path.dirname(finalPath);

        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }

        pres.writeFile({ fileName: finalPath })
            .then(fileName => {
                console.log(`PPT saved to ${finalPath}`);
                res.json({ status: "success", path: finalPath });
            })
            .catch(err => {
                console.error(err);
                res.status(500).json({ error: err.message });
            });

    } catch (e) {
        console.error(e);
        res.status(500).json({ error: e.message });
    }
});

app.get('/health', (req, res) => {
    res.json({ status: "ok", service: "ppt-renderer" });
});

app.listen(PORT, () => {
    console.log(`PPT Renderer listening on port ${PORT}`);
});
