from sqlalchemy import Column, Integer, String, Text, JSON, DateTime
from sqlalchemy.sql import func
from shared.db.base import Base

class Course(Base):
    __tablename__ = "courses"

    id = Column(Integer, primary_key=True, index=True)
    
    # Basic fields
    title = Column(String, index=True)
    description = Column(Text, nullable=True)
    status = Column(String, default="DRAFT")  # DRAFT, PROCESSING, CONTENT_READY, ERROR
    content = Column(JSON, nullable=True)  # canonical_content generated by Gemini
    
    # OBE fields
    course_code = Column(String, unique=True, index=True, nullable=True)  # e.g., XCT3002
    programme = Column(String, nullable=True)  # e.g., "6th Civil"
    # Demo Patch Fields
    program_name = Column(String, nullable=True) # e.g. B.Tech, M.Tech
    course_category = Column(String, nullable=True) # e.g. Theory, Lab
    
    semester = Column(String, nullable=True)   # e.g., "6th Civil"  
    obe_metadata = Column(JSON, nullable=True)  # COs, units, modules structure
    
    # Phase-1 & Phase-2 Fields (JSON Columns for MVP)
    blueprint = Column(JSON, nullable=True)          # Structured extracted syllabus
    generation_spec = Column(JSON, nullable=True)    # User choices: checklist, words, refs
    prompt_data = Column(JSON, nullable=True)        # Versioned prompts
    
    # Phase 2 Output Fields
    slide_plan = Column(JSON, nullable=True)         # Generated SlidePlan
    ppt_artifact = Column(JSON, nullable=True)       # Path/Metadata of generated PPTX
    
    # Phase V0: Evidence & Verification
    evidence_map = Column(JSON, nullable=True)       # Stores EvidenceMap
    verifier_report = Column(JSON, nullable=True)    # Stores VerifierReport
    grounding_strictness = Column(String, default="NORMAL") # STRICT|NORMAL|DRAFT
    finalization_status = Column(String, default="DRAFT")   # DRAFT|VERIFIED|BLOCKED
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Graph SoT (Phase 3)
    course_graph = Column(JSON, nullable=True)
    course_graph_version = Column(Integer, default=1)

class SyllabusTemplate(Base):
    __tablename__ = "syllabus_templates"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True) # e.g. "B.Tech Computer Science"
    program = Column(String)          # e.g. "B.Tech"
    content = Column(Text)            # Raw text or JSON representation
    created_at = Column(DateTime(timezone=True), server_default=func.now())

# --- Phase 2 Tables ---

class GenerationSpec(Base):
    __tablename__ = "generation_specs"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True) # ForeignKey relation omitted for MVP
    
    # Hierarchy & Timing
    hierarchy_scope = Column(JSON) # Selected modules/topics ids
    total_duration = Column(Integer)
    time_distribution = Column(JSON) # { "mod1": 30, "mod2": 45 }
    
    # Pedagogy
    pedagogy_checklist = Column(JSON) # ["definition", "example", "quiz"]
    
    # Output Constraints
    output_constraints = Column(JSON) # { "max_slides": 20, "font_size": 12 }
    
    # Demo Patch Fields
    demo_mode = Column(Integer, default=1) # 1=True, 0=False
    ncrf_level = Column(String, nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class ReferenceAsset(Base):
    __tablename__ = "reference_assets"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True)
    
    # Strict Scoping
    scope_level = Column(String) # "course", "module", "topic"
    module_id = Column(String, nullable=True)
    topic_id = Column(String, nullable=True)
    
    # File Metadata
    filename = Column(String)
    file_path = Column(String) # Path in storage/S3
    file_type = Column(String) # pdf, ppt, txt
    
    # Ingestion Status
    is_indexed = Column(String, default="PENDING") # PENDING, INDEXED, FAILED
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class PromptVersion(Base):
    __tablename__ = "prompt_versions"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True)
    version_num = Column(Integer)
    
    prompt_text = Column(Text)
    spec_snapshot = Column(JSON) # Copy of generation spec used
    
    is_active = Column(Integer, default=1) # 1 if this is the currently selected prompt
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class SlidePlan(Base):
    __tablename__ = "slide_plans"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True)
    prompt_version_id = Column(Integer, nullable=True)
    
    plan_json = Column(JSON) # The generated JSON plan
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class Approval(Base):
    __tablename__ = "approvals"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True)
    entity_type = Column(String) # "PPT_PREVIEW", "FINAL_CONTENT"
    
    status = Column(String) # APPROVED, REJECTED
    comments = Column(Text, nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class TopicGenerationJob(Base):
    __tablename__ = "topic_generation_jobs"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True)
    module_id = Column(String, index=True)
    topic_id = Column(String, index=True)
    
    status = Column(String, default="PENDING") # PENDING, GENERATED, VERIFIED
    version = Column(Integer, default=1)
    
    slides_json = Column(JSON, nullable=True) # Full slide deck for this topic
    pptx_path = Column(String, nullable=True)
    
    reviewer_notes = Column(Text, nullable=True) # Audit trail
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Advanced HITL Fields
    approval_status = Column(String, default="PENDING") # PENDING, APPROVED, REJECTED
    approved_at = Column(DateTime(timezone=True), nullable=True)
    reviewer_id = Column(String, nullable=True)
    rejection_reason = Column(Text, nullable=True)

class GraphEditLog(Base):
    __tablename__ = "graph_edit_logs"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True)
    target_id = Column(String, index=True) # ID of Node edited
    operation = Column(String) # UPDATE, DELETE, ADD
    changes = Column(JSON, nullable=True) # Patch content
    timestamp = Column(DateTime(timezone=True), server_default=func.now())

class JobRun(Base):
    __tablename__ = "job_runs"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True)
    topic_id = Column(String, nullable=True, index=True)
    job_type = Column(String) # GENERATE, BUILD, VALIDATE, EXPORT
    status = Column(String) # RUNNING, COMPLETED, FAILED
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    ended_at = Column(DateTime(timezone=True), nullable=True)
    duration_ms = Column(Integer, nullable=True)
    error_details = Column(Text, nullable=True)

class AuditEvent(Base):
    __tablename__ = "audit_events"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, index=True)
    topic_id = Column(String, nullable=True, index=True)
    action = Column(String) # APPROVE, REJECT, MODIFY
    actor_id = Column(String, nullable=True)
    comment = Column(Text, nullable=True)
    timestamp = Column(DateTime(timezone=True), server_default=func.now())


